# RLingua controller dk_view (doorkey_8x8, view information). Written by gpt-5-mini following RLingua Appendix B.A;
# selected round 2 (16/20 feedback episodes). Generated by scripts/rlingua_controllers_20261005.py.
def controller(obs, memory) -> int:
    """
    Improved staged controller for: go to key, pick it up, go to locked door, unlock/open it, go to goal.

    Bug fixes from previous version:
    - Fixed is_blocking signature to accept (obj, color, state) and updated all calls accordingly.
    - Ensures consistent unpacking of cell() return values when calling is_blocking.
    - Keeps the other improvements: allowing exploration into unseen cells, simple wall-follow
      when carrying key, and staged behaviour.
    """
    from collections import deque

    # Actions
    TURN_LEFT = 0
    TURN_RIGHT = 1
    FORWARD = 2
    PICKUP = 3
    DROP = 4
    TOGGLE = 5
    DONE = 6

    img = obs['image']  # img[x][y] with x=0..6 left->right, y=0..6 top->bottom
    W, H = 7, 7
    agent_x, agent_y = 3, 6  # agent is always at this cell in egocentric view

    # helpers
    def in_bounds(x, y):
        return 0 <= x < W and 0 <= y < H

    def cell(x, y):
        if not in_bounds(x, y):
            return (2, 0, 0)  # treat out-of-bounds as wall
        return img[x][y]  # [object, color, state]

    # what's carried by agent (object at agent cell)
    carried_obj, carried_color, carried_state = cell(agent_x, agent_y)

    # Blocking test for attempting to move forward into a cell:
    # A wall, a closed or locked door, a key, a ball or a box in front blocks forward.
    # We treat unseen (0) as NOT blocking so the agent can explore into unknown cells.
    def is_blocking(obj, color, state):
        if obj == 0:
            return False  # unseen: allow exploring into it
        if obj == 2:  # wall
            return True
        if obj == 4 and state != 0:  # door but not open
            return True
        if obj in (5, 6, 7):  # key/ball/box block
            return True
        if obj == 9:  # lava blocks
            return True
        return False

    # passability used by BFS and immediate checks: allow unseen as traversable (we want exploration)
    def passable(x, y):
        if not in_bounds(x, y):
            return False
        o, c, s = cell(x, y)
        # open door, floor, empty, goal are passable; also allow unseen for exploration
        if o in (1, 3, 8):
            return True
        if o == 4 and s == 0:
            return True
        if o == 0:
            return True
        return False

    # find objects of a given type
    def find_objects(obj_code):
        res = []
        for x in range(W):
            for y in range(H):
                o, c, s = cell(x, y)
                if o == obj_code:
                    res.append((x, y, o, c, s))
        return res

    # BFS to nearest target cell (targets is set of coords). We allow traversal of passable cells.
    def bfs_to_targets(targets):
        start = (agent_x, agent_y)
        if start in targets:
            return [start]
        q = deque([start])
        prev = {start: None}
        while q:
            cur = q.popleft()
            cx, cy = cur
            for dx, dy in ((0, -1), (1, 0), (0, 1), (-1, 0)):
                nx, ny = cx + dx, cy + dy
                if not in_bounds(nx, ny):
                    continue
                if (nx, ny) in prev:
                    continue
                # allow stepping onto target even if currently blocking (e.g., goal)
                if (nx, ny) in targets:
                    prev[(nx, ny)] = cur
                    # reconstruct path
                    path = []
                    node = (nx, ny)
                    while node is not None:
                        path.append(node)
                        node = prev[node]
                    path.reverse()
                    return path
                if passable(nx, ny):
                    prev[(nx, ny)] = cur
                    q.append((nx, ny))
        return None

    # adjacent positions
    def adjacent_positions(x, y):
        res = []
        for dx, dy in ((0, -1), (1, 0), (0, 1), (-1, 0)):
            nx, ny = x + dx, y + dy
            if in_bounds(nx, ny):
                res.append((nx, ny))
        return res

    def find_reachable_adjacent(obj_x, obj_y):
        cand = set()
        for (nx, ny) in adjacent_positions(obj_x, obj_y):
            if (nx, ny) == (agent_x, agent_y) or passable(nx, ny):
                cand.add((nx, ny))
        if not cand:
            return None, None
        path = bfs_to_targets(cand)
        if path is None:
            return None, None
        return path, path[-1]

    # movement primitives relative to current egocentric orientation (agent faces "up")
    def actions_to_step(dx, dy):
        # dx,dy are -1..1 ints: (-1,0)=left, (1,0)=right, (0,-1)=forward, (0,1)=back
        if dx == 0 and dy == -1:
            return [FORWARD]
        if dx == 1 and dy == 0:
            return [TURN_RIGHT, FORWARD]
        if dx == -1 and dy == 0:
            return [TURN_LEFT, FORWARD]
        if dx == 0 and dy == 1:
            return [TURN_RIGHT, TURN_RIGHT, FORWARD]
        return [TURN_RIGHT]

    # Wall-follow (right-hand rule) when searching for the door: make a short plan for this step.
    # Right-hand rule logic (in current egocentric orientation):
    #  - If right cell is free (not blocking), TURN_RIGHT then FORWARD.
    #  - Else if front cell is free, FORWARD.
    #  - Else TURN_LEFT.
    def wall_follow_step_plan():
        # Coordinates in egocentric view:
        # agent at (3,6), forward (3,5), right (4,6), left (2,6)
        fx, fy = 3, 5
        rx, ry = 4, 6
        lx, ly = 2, 6
        # Get cells (treat out of bounds as wall)
        ro, rc, rs = cell(rx, ry) if in_bounds(rx, ry) else (2, 0, 0)
        fo, fc, fs = cell(fx, fy) if in_bounds(fx, fy) else (2, 0, 0)
        # Decide based on blocking test (use is_blocking)
        if not is_blocking(ro, rc, rs):
            return [TURN_RIGHT, FORWARD]
        if not is_blocking(fo, fc, fs):
            return [FORWARD]
        return [TURN_LEFT]

    # Memory initialization
    if memory is None:
        memory = {}
    if 'phase' not in memory:
        memory['phase'] = 1
    if 'plan' not in memory:
        memory['plan'] = []
    if 'step' not in memory:
        memory['step'] = 0
    if 'last_seen_door' not in memory:
        memory['last_seen_door'] = -9999
    if 'wall_follow' not in memory:
        memory['wall_follow'] = False

    # Execute queued low-level plan if present
    if memory.get('plan'):
        act = memory['plan'].pop(0)
        memory['step'] += 1
        return act

    # Update step counter
    memory['step'] += 1

    # Detect door visibility and update last_seen_door
    doors = find_objects(4)
    if doors:
        memory['last_seen_door'] = memory['step']
        memory['wall_follow'] = False  # stop wall-follow if we see the door

    phase = memory['phase']

    # If carrying key but not in phase >=3, advance to phase 3
    if carried_obj == 5 and phase < 3:
        memory['phase'] = 3
        phase = 3

    # PHASE 1: go to the key
    if phase == 1:
        # if already carrying a key, skip to phase 3
        if carried_obj == 5:
            memory['phase'] = 3
            phase = 3
        else:
            keys = find_objects(5)
            if keys:
                kx, ky, _, kcol, kst = keys[0]
                # if key is directly in front, proceed to pickup phase
                if (3, 5) == (kx, ky):
                    memory['phase'] = 2
                    phase = 2
                else:
                    # find reachable adjacent cell to the key
                    path, target = find_reachable_adjacent(kx, ky)
                    if path is None:
                        # cannot reach adjacent cell: simple exploration (allow forward into unseen)
                        fo, fc, fs = cell(3, 5)
                        if not is_blocking(fo, fc, fs):
                            memory['plan'] = [FORWARD]
                        else:
                            memory['plan'] = [TURN_RIGHT]
                        act = memory['plan'].pop(0)
                        return act
                    # move one step along path if not already there
                    if len(path) >= 2:
                        nx, ny = path[1]
                        dx = nx - agent_x
                        dy = ny - agent_y
                        memory['plan'] = actions_to_step(dx, dy)
                        act = memory['plan'].pop(0)
                        return act
                    else:
                        # already adjacent: adjust or pick up if in front
                        if (kx, ky) == (3, 5):
                            memory['phase'] = 2
                            return controller(obs, memory)
                        fo, fc, fs = cell(3, 5)
                        if not is_blocking(fo, fc, fs):
                            memory['plan'] = [FORWARD]
                        else:
                            memory['plan'] = [TURN_RIGHT]
                        act = memory['plan'].pop(0)
                        return act

    # PHASE 2: pick up the key
    if phase == 2:
        if carried_obj == 5:
            memory['phase'] = 3
            phase = 3
        else:
            fx, fy = 3, 5
            fo, fc, fs = cell(fx, fy)
            if fo == 5:
                memory['plan'] = [PICKUP]
                act = memory['plan'].pop(0)
                # after picking up, start wall-follow if door not visible soon
                memory['last_seen_door'] = memory.get('last_seen_door', -9999)
                memory['wall_follow'] = False
                return act
            # reposition to be in front of the key
            keys = find_objects(5)
            if keys:
                kx, ky, _, _, _ = keys[0]
                path, target = find_reachable_adjacent(kx, ky)
                if path is None:
                    fo, fc, fs = cell(3, 5)
                    if not is_blocking(fo, fc, fs):
                        memory['plan'] = [FORWARD]
                    else:
                        memory['plan'] = [TURN_RIGHT]
                    act = memory['plan'].pop(0)
                    return act
                if len(path) >= 2:
                    nx, ny = path[1]
                    dx = nx - agent_x
                    dy = ny - agent_y
                    memory['plan'] = actions_to_step(dx, dy)
                    act = memory['plan'].pop(0)
                    return act
                else:
                    fo, fc, fs = cell(3, 5)
                    if not is_blocking(fo, fc, fs):
                        memory['plan'] = [FORWARD]
                    else:
                        memory['plan'] = [TURN_RIGHT]
                    act = memory['plan'].pop(0)
                    return act
            else:
                # key not visible: explore forward if possible
                fo, fc, fs = cell(3, 5)
                if not is_blocking(fo, fc, fs):
                    memory['plan'] = [FORWARD]
                else:
                    memory['plan'] = [TURN_RIGHT]
                act = memory['plan'].pop(0)
                return act

    # PHASE 3: go to the door (stand adjacent so door is in front)
    if phase == 3:
        # If lost the key (dropped somehow), go back to phase 1
        if carried_obj != 5:
            memory['phase'] = 1
            return controller(obs, memory)

        # If we see a door, go toward it
        doors = find_objects(4)
        if doors:
            # choose the first seen door
            dxo, dyo, _, dcol, dst = doors[0]
            # if door directly in front, go to unlocking
            if (3, 5) == (dxo, dyo):
                memory['phase'] = 4
                memory['wall_follow'] = False
                phase = 4
            else:
                # get reachable adjacent cell and approach it
                path, target = find_reachable_adjacent(dxo, dyo)
                if path is None:
                    # fallback exploration
                    fo, fc, fs = cell(3, 5)
                    if not is_blocking(fo, fc, fs):
                        memory['plan'] = [FORWARD]
                    else:
                        memory['plan'] = [TURN_RIGHT]
                    act = memory['plan'].pop(0)
                    return act
                if len(path) >= 2:
                    nx, ny = path[1]
                    ddx = nx - agent_x
                    ddy = ny - agent_y
                    memory['plan'] = actions_to_step(ddx, ddy)
                    act = memory['plan'].pop(0)
                    return act
                else:
                    # already adjacent, try to align so door is in front
                    if (dxo, dyo) == (3, 5):
                        memory['phase'] = 4
                        return controller(obs, memory)
                    fo, fc, fs = cell(3, 5)
                    if not is_blocking(fo, fc, fs):
                        memory['plan'] = [FORWARD]
                    else:
                        memory['plan'] = [TURN_RIGHT]
                    act = memory['plan'].pop(0)
                    return act
        else:
            # Door not visible. Use wall-following to search for it.
            # Start/continue wall-follow if either recently picked key or door unseen for some steps.
            steps_since_seen = memory['step'] - memory.get('last_seen_door', -9999)
            # enable wall-follow if key held and door hasn't been seen recently
            if carried_obj == 5 and steps_since_seen > 1:
                memory['wall_follow'] = True

            if memory.get('wall_follow', False):
                # produce one wall-follow step plan
                wf_plan = wall_follow_step_plan()
                memory['plan'] = wf_plan
                act = memory['plan'].pop(0)
                return act
            else:
                # basic exploration: move forward into unseen if possible, else turn right
                fo, fc, fs = cell(3, 5)
                if not is_blocking(fo, fc, fs):
                    memory['plan'] = [FORWARD]
                else:
                    memory['plan'] = [TURN_RIGHT]
                act = memory['plan'].pop(0)
                return act

    # PHASE 4: unlock/open the door in front
    if phase == 4:
        fx, fy = 3, 5
        fo, fc, fs = cell(fx, fy)
        # if door not in front anymore, go back to phase 3
        if fo != 4:
            memory['phase'] = 3
            return controller(obs, memory)
        # if locked/closed, toggle it
        if fs != 0:
            memory['plan'] = [TOGGLE]
            act = memory['plan'].pop(0)
            return act
        else:
            # door already open: go through
            memory['phase'] = 5
            phase = 5

    # PHASE 5: go through doorway to the goal
    if phase == 5:
        fx, fy = 3, 5
        fo, fc, fs = cell(fx, fy)
        # If there's an open door in front, step through it
        if fo == 4 and fs == 0:
            memory['plan'] = [FORWARD]
            act = memory['plan'].pop(0)
            return act
        # If goal visible, path to it
        goals = find_objects(8)
        if goals:
            gx, gy, _, gcol, gst = goals[0]
            if (gx, gy) == (3, 5):
                memory['plan'] = [FORWARD]
                act = memory['plan'].pop(0)
                return act
            path = bfs_to_targets({(gx, gy)})
            if path is None:
                fo, fc, fs = cell(3, 5)
                if not is_blocking(fo, fc, fs):
                    memory['plan'] = [FORWARD]
                else:
                    memory['plan'] = [TURN_RIGHT]
                act = memory['plan'].pop(0)
                return act
            if len(path) >= 2:
                nx, ny = path[1]
                dx = nx - agent_x
                dy = ny - agent_y
                memory['plan'] = actions_to_step(dx, dy)
                act = memory['plan'].pop(0)
                return act
            else:
                memory['plan'] = [DONE]
                act = memory['plan'].pop(0)
                return act
        else:
            # Goal not visible yet: move forward into open/unseen to explore
            fo, fc, fs = cell(3, 5)
            if not is_blocking(fo, fc, fs):
                memory['plan'] = [FORWARD]
            else:
                memory['plan'] = [TURN_RIGHT]
            act = memory['plan'].pop(0)
            return act

    # Fallback safe behaviour: try to move forward into unseen/open if possible, else turn right
    fo, fc, fs = cell(3, 5)
    if not is_blocking(fo, fc, fs):
        return FORWARD
    else:
        return TURN_RIGHT
