# RLingua controller kc_view (keycorridor_s3r3, view information). Written by gpt-5-mini following RLingua Appendix B.A;
# selected round 2 (4/20 feedback episodes). Generated by scripts/rlingua_controllers_20261005.py.
import random

def controller(obs, memory) -> int:
    """
    Improved staged controller that more reliably finds an empty cell to drop the key
    and avoids getting stuck in repeated forward/turn patterns near doors.

    Stages:
      1: explore to find key
      2: go to key
      4: explore/find locked door (matching key color)
      5: go to locked door
      6: unlock the locked door (toggle)
      7: find an empty cell and drop the key there
      8: search/go to ball
      9: pick up the ball

    Actions:
      0 turn_left, 1 turn_right, 2 forward, 3 pickup, 4 drop, 5 toggle, 6 done
    """
    # Object codes (from problem)
    OBJ_UNSEEN = 0
    OBJ_EMPTY = 1
    OBJ_WALL = 2
    OBJ_FLOOR = 3
    OBJ_DOOR = 4
    OBJ_KEY = 5
    OBJ_BALL = 6
    OBJ_BOX = 7
    OBJ_GOAL = 8
    OBJ_LAVA = 9
    OBJ_AGENT = 10

    image = obs['image']

    # Initialize memory
    if 'stage' not in memory:
        memory.update({
            'stage': 1,
            'key_color': None,
            'target_rel': None,
            'last_action': None,
            'repeat': 0,
            'hist': [],
            'stuck_count': 0,       # counts timesteps without meaningful progress while carrying key
            'steps_since_event': 0, # generic progress timer
        })

    def in_bounds(i, j):
        return 0 <= i < 7 and 0 <= j < 7

    def rel_to_ij(dx, dy):
        i = 3 + dx
        j = 6 + dy
        return i, j

    def ij_to_rel(i, j):
        dx = i - 3
        dy = j - 6
        return dx, dy

    def get_cell_by_rel(dx, dy):
        i, j = rel_to_ij(dx, dy)
        if not in_bounds(i, j):
            return (OBJ_UNSEEN, 0, 0)
        return tuple(image[i][j])

    def get_cell_front():
        return get_cell_by_rel(0, -1)

    def carrying():
        return image[3][6][0]  # carried object code; 1 = nothing

    def can_forward(cell):
        obj, col, state = cell
        if obj in (OBJ_EMPTY, OBJ_FLOOR, OBJ_GOAL):
            return True
        if obj == OBJ_DOOR and state == 0:
            return True
        return False

    def find_all_objects(obj_codes=None, state_eq=None, color_eq=None):
        res = []
        for i in range(7):
            for j in range(7):
                o, c, s = image[i][j]
                if o == OBJ_UNSEEN:
                    continue
                if obj_codes is not None and o not in obj_codes:
                    continue
                if state_eq is not None and s != state_eq:
                    continue
                if color_eq is not None and c != color_eq:
                    continue
                dx, dy = ij_to_rel(i, j)
                res.append((dx, dy, o, c, s))
        res.sort(key=lambda x: (abs(x[0]) + abs(x[1]), abs(x[1]), abs(x[0])))
        return res

    def find_nearest(obj_codes=None, state_eq=None, color_eq=None):
        lst = find_all_objects(obj_codes=obj_codes, state_eq=state_eq, color_eq=color_eq)
        return lst[0] if lst else None

    def orient_towards(dx, dy):
        """
        Reactive steering to face/move toward a relative target (dx,dy).
        Returns one action among {0,1,2,5} or rotations.
        """
        front = get_cell_front()
        # If target is straight ahead (same column, above)
        if dx == 0 and dy < 0:
            # If forward is passable, move forward
            if can_forward(front):
                return 2
            # If a closed door is in front, open it
            if front[0] == OBJ_DOOR and front[2] == 1:
                return 5
            # If a locked door in front and we have key, unlock (handled by stage logic otherwise)
            if front[0] == OBJ_DOOR and front[2] == 2:
                return 5
            # Otherwise rotate to search
            return random.choice([0, 1])
        # If target to left/right, rotate accordingly
        if dx < 0:
            return 0
        if dx > 0:
            return 1
        # Target is behind or same cell: rotate left to reorient
        return 0

    # choose_action: handle repeat detection and simple anti-stuck adaptation
    def choose_action(action, meaningful=False):
        last = memory.get('last_action')
        repeat = memory.get('repeat', 0)
        hist = memory.get('hist', [])
        stuck = memory.get('stuck_count', 0)

        # Update repeat count
        if action == last:
            repeat += 1
        else:
            repeat = 1

        # If action is meaningful (pickup/drop/toggle), reset stuck counters
        if meaningful:
            stuck = 0
            memory['steps_since_event'] = 0
        else:
            memory['steps_since_event'] = memory.get('steps_since_event', 0) + 1

        # Basic anti-stuck policies:
        front_cell = get_cell_front()
        # If we are repeating the same rotation 4+ times, try the opposite rotation or forward if possible
        if repeat >= 4 and action in (0, 1):
            if can_forward(front_cell):
                action = 2
            else:
                action = 0 if action == 1 else 1
            repeat = 1

        # If stuck_count large, force different actions
        if memory.get('stuck_count', 0) >= 8:
            if can_forward(front_cell):
                action = 2
            else:
                action = random.choice([0, 1])
            repeat = 1
            stuck = 0  # try to escape

        # Update hist and memory
        hist.append(action)
        if len(hist) > 16:
            hist.pop(0)
        memory['hist'] = hist
        memory['last_action'] = action
        memory['repeat'] = repeat
        memory['stuck_count'] = stuck
        return action

    # Helper: declare an action meaningful to reset stuck counters
    def choose_meaningful(action):
        return choose_action(action, meaningful=True)

    # Get basic info
    front = get_cell_front()
    current_carry = carrying()
    stage = memory['stage']

    # Quick state corrections and transitions
    # If carrying key, ensure stage >=4
    if current_carry == OBJ_KEY and stage < 4:
        memory['stage'] = 4
        stage = 4

    # If we've previously progressed to 'dropped key' (no longer carrying) then go to ball search
    if current_carry != OBJ_KEY and stage >= 7:
        memory['stage'] = 8
        stage = 8

    # If we lost the key unexpectedly (not carrying) but were in later stages, restart search
    if current_carry != OBJ_KEY and stage in (4,5,6,7):
        # It's possible we've dropped/placed it already; if not, go back to searching
        # We'll conservatively move to stage 1 (find key) if we don't know a key color.
        if memory.get('key_color') is None:
            memory['stage'] = 1
            stage = 1

    # If carrying key but no color stored, try to deduce color from any visible key
    if current_carry == OBJ_KEY and memory.get('key_color') is None:
        kseen = find_nearest(obj_codes=[OBJ_KEY])
        if kseen:
            memory['key_color'] = kseen[3]

    # If ball seen and we are allowed to pick it (not carrying key), prefer it
    ball_seen = find_nearest(obj_codes=[OBJ_BALL])
    if ball_seen and current_carry != OBJ_KEY and stage < 9:
        memory['target_rel'] = (ball_seen[0], ball_seen[1])
        # If ball is directly in front, pick it immediately
        if ball_seen[0] == 0 and ball_seen[1] == -1 and front[0] == OBJ_BALL:
            memory['stage'] = 9
            return choose_meaningful(3)

    # STAGE 1: explore to find key
    if stage == 1:
        key_seen = find_nearest(obj_codes=[OBJ_KEY])
        if key_seen:
            dx, dy, o, c, s = key_seen
            memory['key_color'] = c
            memory['target_rel'] = (dx, dy)
            memory['stage'] = 2
            return choose_action(orient_towards(dx, dy))
        # Open closed door in front to explore further
        if front[0] == OBJ_DOOR and front[2] == 1:
            return choose_meaningful(5)
        # Move forward if possible, else rotate (alternate)
        if can_forward(front):
            return choose_action(2)
        return choose_action(random.choice([0, 1]))

    # STAGE 2: go to key & pick it up
    if stage == 2:
        if current_carry == OBJ_KEY:
            memory['stage'] = 4
            return choose_action(random.choice([0, 1]))
        key_seen = find_nearest(obj_codes=[OBJ_KEY])
        if not key_seen:
            memory['stage'] = 1
            return choose_action(random.choice([0, 1]))
        dx, dy, o, c, s = key_seen
        memory['target_rel'] = (dx, dy)
        # If key in front, pick it
        if dx == 0 and dy == -1 and front[0] == OBJ_KEY:
            memory['key_color'] = c
            return choose_meaningful(3)
        # If a closed door blocks front, open it
        if front[0] == OBJ_DOOR and front[2] == 1:
            return choose_meaningful(5)
        # If locked door blocks but we don't have key yet, try circumventing
        if front[0] == OBJ_DOOR and front[2] == 2:
            return choose_action(random.choice([0, 1]))
        return choose_action(orient_towards(dx, dy))

    # STAGE 4: search/find locked door of key color
    if stage == 4:
        kcol = memory.get('key_color')
        # If we don't know key color but carry key, we might still deduce from any key seen
        if current_carry == OBJ_KEY and kcol is None:
            kseen = find_nearest(obj_codes=[OBJ_KEY])
            if kseen:
                memory['key_color'] = kseen[3]
                kcol = kseen[3]
        lock_seen = find_nearest(obj_codes=[OBJ_DOOR], state_eq=2, color_eq=kcol)
        if lock_seen:
            dx, dy, _, _, _ = lock_seen
            memory['target_rel'] = (dx, dy)
            memory['stage'] = 5
            return choose_action(orient_towards(dx, dy))
        # Explore: open closed doors encountered
        if front[0] == OBJ_DOOR and front[2] == 1:
            return choose_meaningful(5)
        if can_forward(front):
            return choose_action(2)
        return choose_action(random.choice([0, 1]))

    # STAGE 5: go to locked door
    if stage == 5:
        kcol = memory.get('key_color')
        lock_seen = find_nearest(obj_codes=[OBJ_DOOR], state_eq=2, color_eq=kcol)
        if not lock_seen:
            memory['stage'] = 4
            return choose_action(random.choice([0, 1]))
        dx, dy, o, c, s = lock_seen
        memory['target_rel'] = (dx, dy)
        # If the locked door is exactly in front, and we carry matching key, unlock
        if dx == 0 and dy == -1 and front[0] == OBJ_DOOR and front[2] == 2:
            if current_carry == OBJ_KEY and memory.get('key_color') == front[1]:
                memory['stage'] = 6
                return choose_meaningful(5)
            else:
                # We can't open; go back to searching
                memory['stage'] = 4
                return choose_action(random.choice([0, 1]))
        # If closed door in front (not locked), open
        if front[0] == OBJ_DOOR and front[2] == 1:
            return choose_meaningful(5)
        # If forward passable, step forward; else steer
        return choose_action(orient_towards(dx, dy))

    # STAGE 6: unlocked the door; step in and then find empty cell to drop
    if stage == 6:
        # If front is still locked (possible if toggle failed), try again
        if front[0] == OBJ_DOOR and front[2] == 2:
            if current_carry == OBJ_KEY and memory.get('key_color') == front[1]:
                return choose_meaningful(5)
            memory['stage'] = 4
            return choose_action(random.choice([0, 1]))
        # If forward is passable, step forward into the room to start looking for an empty cell
        if can_forward(front):
            # move into the room; after moving we will search for an empty tile to drop the key
            memory['stage'] = 7
            return choose_action(2)
        # Otherwise rotate a bit to find the door opening
        return choose_action(random.choice([0, 1]))

    # STAGE 7: find an OBJ_EMPTY cell and drop the key on it
    # Note: per task, drop must be onto an empty cell (OBJ_EMPTY). We search for any visible empty cell,
    # navigate to make it the front cell, then drop.
    if stage == 7:
        if current_carry != OBJ_KEY:
            memory['stage'] = 8
            return choose_action(random.choice([0, 1]))

        # Look for visible empty cells (strict OBJ_EMPTY)
        empty_seen = find_nearest(obj_codes=[OBJ_EMPTY])
        if empty_seen:
            edx, edy, o, c, s = empty_seen
            memory['target_rel'] = (edx, edy)
            # If that empty cell is directly in front and indeed OBJ_EMPTY, drop
            if edx == 0 and edy == -1:
                front_now = get_cell_front()
                if front_now[0] == OBJ_EMPTY:
                    # Drop key here
                    memory['stage'] = 8
                    return choose_meaningful(4)
                # If it was targeted but is no longer empty, fall back to navigating
            # If empty cell is behind us (dy >= 0), rotate toward it by steering
            # Use orient_towards to approach the empty cell
            return choose_action(orient_towards(edx, edy))
        else:
            # If no empty cell seen, systematically explore the immediate area:
            # Prefer stepping forward into rooms; open closed doors encountered.
            # Also increment stuck_count if we make moves that don't help.
            if front[0] == OBJ_DOOR and front[2] == 1:
                return choose_meaningful(5)
            if can_forward(front):
                # Move forward to try to reveal empty tiles
                action = choose_action(2)
                # If we keep moving forward while still carrying key and haven't seen an empty cell for many steps,
                # increment stuck_count to trigger escape later
                if current_carry == OBJ_KEY:
                    memory['stuck_count'] = memory.get('stuck_count', 0) + 1
                return action
            # If blocked, rotate to look for empty spaces
            return choose_action(random.choice([0, 1]))

    # STAGE 8: search/go to ball (after key dropped)
    if stage == 8:
        # if carrying key somehow, go back to trying to drop
        if current_carry == OBJ_KEY:
            memory['stage'] = 7
            return choose_action(random.choice([0, 1]))
        ball = find_nearest(obj_codes=[OBJ_BALL])
        if ball:
            dx, dy, o, c, s = ball
            memory['target_rel'] = (dx, dy)
            # if ball in front, pick it
            if dx == 0 and dy == -1 and front[0] == OBJ_BALL:
                memory['stage'] = 9
                return choose_meaningful(3)
            return choose_action(orient_towards(dx, dy))
        # explore if no ball visible
        if front[0] == OBJ_DOOR and front[2] == 1:
            return choose_meaningful(5)
        if can_forward(front):
            return choose_action(2)
        return choose_action(random.choice([0, 1]))

    # STAGE 9: pick up the ball
    if stage == 9:
        if front[0] == OBJ_BALL and current_carry != OBJ_KEY:
            return choose_meaningful(3)
        ball = find_nearest(obj_codes=[OBJ_BALL])
        if ball:
            dx, dy, o, c, s = ball
            return choose_action(orient_towards(dx, dy))
        if can_forward(front):
            return choose_action(2)
        return choose_action(random.choice([0, 1]))

    # Default fallback
    if front[0] == OBJ_DOOR and front[2] == 1:
        return choose_meaningful(5)
    if can_forward(front):
        return choose_action(2)
    return choose_action(random.choice([0, 1]))
