# RLingua controller mr_view (multiroom_n6, view information). Written by gpt-5-mini following RLingua Appendix B.A;
# selected round 0 (0/20 feedback episodes). Generated by scripts/rlingua_controllers_20261005.py.
def controller(obs, memory) -> int:
    """
    Staged controller implementing the phases:
    Phase 1: open door in front
    Phase 2: go through the door
    Phase 3: open the door in front
    Phase 4: go through the door
    Phase 5: open the door in front
    Phase 6: go through the door
    Phase 7: open the door in front
    Phase 8: go through the door
    Phase 9: open the door in front
    Phase 10: go through the door
    Phase 11: go to the green goal square in the last room

    The controller uses obs['image'] and memory['phase'] to decide actions.
    """
    # Initialize phase
    phase = memory.get('phase', 1)

    image = obs['image']  # image[i][j] with i=col 0..6 left->right, j=row 0..6 top->bottom
    # Agent is at image[3][6], facing up; front cell is image[3][5]
    front = image[3][5]   # [object, color, state]
    carry = image[3][6]   # the carried object representation [object, color, state]
    carry_obj = carry[0]
    carry_color = carry[1]

    # helpers
    def find_objects(obj_id):
        # return list of (col,row,color) positions where object==obj_id
        res = []
        for i in range(7):
            for j in range(7):
                cell = image[i][j]
                if cell[0] == obj_id:
                    res.append((i, j, cell[1]))
        return res

    def front_is_floor_or_empty_or_goal_or_open_door():
        # forward moves allowed only if the front cell is empty floor, open door or the goal
        o = front[0]
        if o == 1 or o == 3 or o == 8:
            return True
        if o == 4 and front[2] == 0:  # door and open
            return True
        return False

    # We'll allow the controller to update phase and possibly immediately act in the same call.
    # But to avoid infinite immediate loops, limit the number of phase transitions in one call.
    transition_budget = 8
    while transition_budget > 0:
        transition_budget -= 1

        # Odd phases: open the door in front
        if phase in (1, 3, 5, 7, 9):
            # If front is a door
            if front[0] == 4:
                door_state = front[2]  # 0 open, 1 closed, 2 locked
                door_color = front[1]
                # Already open -> advance to go-through phase
                if door_state == 0:
                    phase += 1
                    memory['phase'] = phase
                    # continue loop to handle the new even (go-through) phase immediately
                    continue
                # Closed -> toggle to open
                if door_state == 1:
                    memory['phase'] = phase
                    return 5  # toggle
                # Locked -> try to unlock if carrying a key of same color
                if door_state == 2:
                    if carry_obj == 5 and carry_color == door_color:
                        memory['phase'] = phase
                        return 5  # toggle unlock
                    # if we see a matching key somewhere in view, start scanning/turning to try to reach it
                    keys = find_objects(5)
                    matching_keys = [k for k in keys if k[2] == door_color]
                    if matching_keys:
                        # rotate to search for the key (alternate left/right to avoid repeating the same turn)
                        toggle = memory.get('search_turn_toggle', 0)
                        memory['search_turn_toggle'] = 1 - toggle
                        memory['phase'] = phase
                        return 0 if toggle == 0 else 1
                    # no matching key in view and not carrying -> turn left to explore (avoid repeated useless toggles)
                    memory['phase'] = phase
                    return 0
            else:
                # No door in front (unexpected) -> advance to next phase
                phase += 1
                memory['phase'] = phase
                continue

        # Even phases: go through the door (move forward into next room)
        elif phase in (2, 4, 6, 8, 10):
            # If forward is allowed (floor, open door or goal) -> move forward and advance phase
            if front_is_floor_or_empty_or_goal_or_open_door():
                memory['phase'] = phase + 1
                return 2  # forward
            # If front is a closed door -> open it
            if front[0] == 4 and front[2] == 1:
                memory['phase'] = phase
                return 5  # toggle open closed door
            # If front is a locked door -> try to unlock if carrying matching key; otherwise try to search for key
            if front[0] == 4 and front[2] == 2:
                door_color = front[1]
                if carry_obj == 5 and carry_color == door_color:
                    memory['phase'] = phase
                    return 5  # toggle unlock
                # search for key in view
                keys = find_objects(5)
                matching_keys = [k for k in keys if k[2] == door_color]
                if matching_keys:
                    toggle = memory.get('search_turn_toggle', 0)
                    memory['search_turn_toggle'] = 1 - toggle
                    memory['phase'] = phase
                    return 0 if toggle == 0 else 1
                # otherwise try to turn to find another route / avoid repeatedly toggling a locked door without key
                memory['phase'] = phase
                return 0
            # If blocked by an object that cannot be moved into (wall, closed door, box, ball, key) -> try to turn and maneuver
            memory['phase'] = phase
            return 0

        # Final phase: go to the green goal square in the last room
        elif phase == 11:
            # If goal is directly in front -> step forward
            if front[0] == 8:
                memory['phase'] = phase
                return 2  # forward into goal (will end episode)
            # If goal visible somewhere in view, try to orient/move towards it:
            goals = find_objects(8)
            if goals:
                gx, gy, _ = goals[0]
                # If goal is roughly ahead in same column (col==3) and above agent -> move forward
                if gx == 3 and gy < 6:
                    # If there's an immediate blocking object in front, handle it
                    if front_is_floor_or_empty_or_goal_or_open_door():
                        memory['phase'] = phase
                        return 2
                    # If a door is blocking, open/unlock if possible
                    if front[0] == 4:
                        if front[2] == 1:
                            return 5
                        if front[2] == 2:
                            if carry_obj == 5 and carry_color == front[1]:
                                return 5
                            else:
                                # rotate to search for key
                                toggle = memory.get('search_turn_toggle', 0)
                                memory['search_turn_toggle'] = 1 - toggle
                                memory['phase'] = phase
                                return 0 if toggle == 0 else 1
                    # otherwise try to move forward (if safe) or turn
                    memory['phase'] = phase
                    return 0
                else:
                    # goal not directly ahead in current view orientation -> turn to scan
                    toggle = memory.get('goal_scan_toggle', 0)
                    memory['goal_scan_toggle'] = 1 - toggle
                    memory['phase'] = phase
                    return 0 if toggle == 0 else 1
            else:
                # goal not visible: try to progress forward if possible, else turn to explore
                if front_is_floor_or_empty_or_goal_or_open_door():
                    memory['phase'] = phase
                    return 2
                else:
                    memory['phase'] = phase
                    return 0

        else:
            # Unknown phase: reset to phase 1
            phase = 1
            memory['phase'] = 1
            continue

    # Fallback: if we somehow exhausted transition budget, just try to turn left to avoid being idle
    memory['phase'] = phase
    return 0
