# RLingua controller dk_full (doorkey_8x8, full information). Written by gpt-5-mini following RLingua Appendix B.A;
# selected round 0 (20/20 feedback episodes). Generated by scripts/rlingua_controllers_20261005.py.
from collections import deque
import math

A_LEFT = 0
A_RIGHT = 1
A_FORWARD = 2
A_PICKUP = 3
A_DROP = 4
A_TOGGLE = 5
A_DONE = 6

def controller(state) -> int:
    grid = state['grid']
    H = state['height']
    W = state['width']
    ax, ay = state['agent_pos']
    ad = state['agent_dir']
    carrying = state['carrying']  # None or dict with 'type' and 'color'

    # Helpers
    def in_bounds(x, y):
        return 0 <= x < W and 0 <= y < H

    def cell_at(x, y):
        if not in_bounds(x, y):
            return None
        return grid[y][x]

    def is_passable(x, y):
        # Passable for forward movement: empty floor (None), goal, or an open door
        c = cell_at(x, y)
        if c is None:
            return True
        t = c.get('type')
        if t == 'goal':
            return True
        if t == 'door' and c.get('is_open', False):
            return True
        return False

    # Direction helpers
    DIRS = [(1, 0), (0, 1), (-1, 0), (0, -1)]  # 0 east,1 south,2 west,3 north

    def dir_to(dx, dy):
        for i, (mx, my) in enumerate(DIRS):
            if (mx, my) == (dx, dy):
                return i
        return None

    def neighbor_positions(x, y):
        for d, (dx, dy) in enumerate(DIRS):
            nx, ny = x + dx, y + dy
            yield d, nx, ny

    # BFS to any of target_cells (set of (x,y)); returns path as list of (x,y) from start to target inclusive
    def bfs_to_targets(start, target_cells):
        sx, sy = start
        if (sx, sy) in target_cells:
            return [(sx, sy)]
        q = deque()
        q.append((sx, sy))
        prev = { (sx, sy): None }
        while q:
            x, y = q.popleft()
            for _, nx, ny in neighbor_positions(x, y):
                if not in_bounds(nx, ny):
                    continue
                if (nx, ny) in prev:
                    continue
                # allow stepping into start even if it's occupied
                if (nx, ny) != (sx, sy) and not is_passable(nx, ny):
                    continue
                prev[(nx, ny)] = (x, y)
                if (nx, ny) in target_cells:
                    # reconstruct path
                    path = [(nx, ny)]
                    cur = (x, y)
                    while cur is not None:
                        path.append(cur)
                        cur = prev[cur]
                    path.reverse()
                    return path
                q.append((nx, ny))
        return None

    # Find positions of objects
    key_positions = []
    doors = []  # list of (x,y,cell)
    goal_pos = None

    for y in range(H):
        for x in range(W):
            c = grid[y][x]
            if c is None:
                continue
            t = c.get('type')
            if t == 'key':
                key_positions.append((x, y, c))
            elif t == 'door':
                doors.append((x, y, c))
            elif t == 'goal':
                goal_pos = (x, y)

    # Utility to find nearest key (by BFS distance)
    def find_nearest_key():
        if not key_positions:
            return None
        keys = [(x, y) for (x, y, _) in key_positions]
        # build adjacency target cells: we want to stand in a cell adjacent to the key
        # pick the reachable adjacency cell with shortest path
        best = None
        best_path = None
        for kx, ky in keys:
            adj_cells = set()
            for _, nx, ny in neighbor_positions(kx, ky):
                if in_bounds(nx, ny) and is_passable(nx, ny):
                    adj_cells.add((nx, ny))
            if not adj_cells:
                continue
            path = bfs_to_targets((ax, ay), adj_cells)
            if path is None:
                continue
            if best_path is None or len(path) < len(best_path):
                best_path = path
                best = (kx, ky)
        if best is None:
            return None
        return best, best_path  # returns key pos and path to adjacency

    # Utility to find the locked or target door (we pick the locked one if exists, otherwise any door along the wall)
    door_target = None
    for (dx, dy, dc) in doors:
        # prefer locked doors, otherwise pick the first door
        if dc.get('is_locked', False):
            door_target = (dx, dy, dc)
            break
    if door_target is None and doors:
        door_target = doors[0]

    # Decide phase and next action
    # Phase logic described in the prompt:
    # - If not carrying key: go to key and pick up
    # - If carrying key: go to door, face and toggle (to unlock/open), then go to goal

    # 1) If not carrying a key: navigate to key adjacency and pick up
    if carrying is None or carrying.get('type') != 'key':
        # Find nearest key and path to adjacency
        res = find_nearest_key()
        if res is None:
            # No reachable key; as fallback, if there's a door open path to goal, try to go to goal
            if goal_pos is not None:
                path_to_goal = bfs_to_targets((ax, ay), {goal_pos})
                if path_to_goal:
                    # move along path
                    if len(path_to_goal) > 1:
                        nx, ny = path_to_goal[1]
                        desired = dir_to(nx - ax, ny - ay)
                        diff = (desired - ad) % 4
                        if diff == 0:
                            return A_FORWARD
                        if diff == 3:
                            return A_LEFT
                        return A_RIGHT
                    else:
                        return A_DONE
            return A_DONE

        (kx, ky), path = res
        # If already standing in the adjacency cell of the key
        if path is not None and len(path) == 1:
            # We're in a cell adjacent to key. Check if key is in front; if so, pick up.
            dx = kx - ax
            dy = ky - ay
            desired_dir = dir_to(dx, dy)
            if desired_dir is None:
                # should not happen, but safe fallback
                return A_DONE
            if ad == desired_dir:
                # Key must be in front to pickup; double-check that cell in front contains a key
                fx, fy = ax + DIRS[ad][0], ay + DIRS[ad][1]
                fc = cell_at(fx, fy)
                if fc is not None and fc.get('type') == 'key':
                    return A_PICKUP
                else:
                    # No key in front; maybe key was taken or moved — replan next tick
                    return A_DONE
            else:
                # rotate towards the key
                diff = (desired_dir - ad) % 4
                if diff == 3:
                    return A_LEFT
                else:
                    return A_RIGHT
        else:
            # Need to move along the path towards adjacency cell
            if path is None:
                return A_DONE
            if len(path) > 1:
                nx, ny = path[1]
                desired = dir_to(nx - ax, ny - ay)
                diff = (desired - ad) % 4
                if diff == 0:
                    return A_FORWARD
                if diff == 3:
                    return A_LEFT
                return A_RIGHT
            else:
                # path length 1 already handled; fallback
                return A_DONE

    # 2) carrying a key: approach door, face it and toggle; after opened go to goal
    else:
        # carrying a key
        # First, if there's a door target use it; else go directly to goal
        if door_target is not None:
            dx, dy, dcell = door_target
            # If door is open, treat as passable and head to goal
            if dcell.get('is_open', False) and goal_pos is not None:
                # go to goal
                path = bfs_to_targets((ax, ay), {goal_pos})
                if path is None:
                    return A_DONE
                if len(path) > 1:
                    nx, ny = path[1]
                    desired = dir_to(nx - ax, ny - ay)
                    diff = (desired - ad) % 4
                    if diff == 0:
                        return A_FORWARD
                    if diff == 3:
                        return A_LEFT
                    return A_RIGHT
                else:
                    # already at goal
                    return A_DONE
            # If door is closed (open == False), we should go to adjacency and toggle
            # Build adjacency cells for door
            adj_cells = set()
            for _, nx, ny in neighbor_positions(dx, dy):
                if in_bounds(nx, ny) and is_passable(nx, ny):
                    adj_cells.add((nx, ny))
            if not adj_cells:
                # cannot reach adjacency; perhaps door is on agent's cell? Unlikely. Fallback go to goal if possible
                if goal_pos is not None:
                    path = bfs_to_targets((ax, ay), {goal_pos})
                    if path and len(path) > 1:
                        nx, ny = path[1]
                        desired = dir_to(nx - ax, ny - ay)
                        diff = (desired - ad) % 4
                        if diff == 0:
                            return A_FORWARD
                        if diff == 3:
                            return A_LEFT
                        return A_RIGHT
                return A_DONE
            path = bfs_to_targets((ax, ay), adj_cells)
            if path is None:
                # not reachable; give up
                return A_DONE
            # If we're at adjacency cell already
            if len(path) == 1:
                # face the door
                ddx = dx - ax
                ddy = dy - ay
                desired_dir = dir_to(ddx, ddy)
                if desired_dir is None:
                    return A_DONE
                if ad == desired_dir:
                    # If door in front and is closed, try to toggle (unlock if necessary)
                    fx, fy = ax + DIRS[ad][0], ay + DIRS[ad][1]
                    fc = cell_at(fx, fy)
                    if fc is None or fc.get('type') != 'door':
                        # weird; maybe door moved; fallback
                        return A_DONE
                    # If door is locked, ensure we have correct key color
                    if fc.get('is_open', False):
                        # door already open: proceed to goal next tick
                        if goal_pos is not None:
                            gpath = bfs_to_targets((ax, ay), {goal_pos})
                            if gpath and len(gpath) > 1:
                                nx, ny = gpath[1]
                                desired = dir_to(nx - ax, ny - ay)
                                diff = (desired - ad) % 4
                                if diff == 0:
                                    return A_FORWARD
                                if diff == 3:
                                    return A_LEFT
                                return A_RIGHT
                            else:
                                return A_DONE
                        return A_DONE
                    # If door is locked, check key color
                    if fc.get('is_locked', False):
                        if carrying and carrying.get('type') == 'key' and carrying.get('color') == fc.get('color'):
                            return A_TOGGLE
                        else:
                            # wrong key; nothing sensible to do
                            return A_DONE
                    else:
                        # door unlocked but closed -> toggle to open
                        return A_TOGGLE
                else:
                    # rotate towards door
                    diff = (desired_dir - ad) % 4
                    if diff == 3:
                        return A_LEFT
                    else:
                        return A_RIGHT
            else:
                # Follow path towards adjacency
                nx, ny = path[1]
                desired = dir_to(nx - ax, ny - ay)
                diff = (desired - ad) % 4
                if diff == 0:
                    return A_FORWARD
                if diff == 3:
                    return A_LEFT
                return A_RIGHT
        else:
            # No door found (shouldn't happen); just head to goal
            if goal_pos is None:
                return A_DONE
            path = bfs_to_targets((ax, ay), {goal_pos})
            if path is None:
                return A_DONE
            if len(path) > 1:
                nx, ny = path[1]
                desired = dir_to(nx - ax, ny - ay)
                diff = (desired - ad) % 4
                if diff == 0:
                    return A_FORWARD
                if diff == 3:
                    return A_LEFT
                return A_RIGHT
            else:
                return A_DONE
