# RLingua controller dk_view (doorkey_8x8, view information). Written by gpt-5-mini following RLingua Appendix B.A;
# selected round 3 (10/20 alone, 19/20 with another policy acting). Generated by scripts/rlingua_controllers_20261005.py.
from collections import deque

def controller(obs, memory) -> int:
    # ACTIONS: 0 turn_left, 1 turn_right, 2 forward, 3 pickup, 4 drop, 5 toggle, 6 done
    img = obs['image']    # img[x][y] with x=0..6 left->right, y=0..6 top->bottom
    last_action = obs.get('last_action', None)

    AG_X, AG_Y = 3, 6  # agent is always at this egocentric position facing 'up' in the image

    # Initialize memory entries
    memory.setdefault('phase', 1)         # 1: seek key, 3: open/unlock door, 4: go to goal
    memory.setdefault('stuck_steps', 0)   # count of consecutive steps with identical view
    memory.setdefault('last_view', None)
    memory.setdefault('turn_pref', 1)     # 1 prefer right turns, 0 prefer left
    memory.setdefault('last_output', None)

    # Helpers to access image cells
    def cell(x, y):
        if 0 <= x < 7 and 0 <= y < 7:
            return img[x][y]
        return (0, 0, 0)

    def front_cell():
        return cell(AG_X, AG_Y - 1)

    # Traversability for moving forward into that cell
    def is_traversable(o, s):
        if o in (1, 3, 8):  # empty, floor, goal
            return True
        if o == 4 and s == 0:  # door open
            return True
        return False

    # Visible hash to detect view changes
    def visible_hash():
        vals = []
        for x in range(7):
            for y in range(7):
                o, c, s = img[x][y]
                if o != 0:
                    vals.append((x, y, o, c, s))
        return tuple(vals)

    # Update stuck/view-change detection
    vh = visible_hash()
    if memory['last_view'] is None or memory['last_view'] != vh:
        memory['last_view'] = vh
        memory['stuck_steps'] = 0
    else:
        memory['stuck_steps'] += 1

    # If stuck for a while, flip turning preference to escape loops
    if memory['stuck_steps'] >= 8:
        memory['turn_pref'] = 1 - memory['turn_pref']
        memory['stuck_steps'] = 0

    # Find all visible objects of a type
    def find_all(obj_type):
        res = []
        for x in range(7):
            for y in range(7):
                o, c, s = img[x][y]
                if o == obj_type:
                    res.append((x, y, c, s))
        return res

    # Manhattan
    def manhattan(a, b):
        return abs(a[0] - b[0]) + abs(a[1] - b[1])

    # Determine carried object (image[3][6])
    carried_obj, carried_col, carried_state = img[3][6]
    carrying_key = (carried_obj == 5)

    # Phase decision
    if not carrying_key:
        memory['phase'] = 1
    else:
        # if open door or goal visible, go to goal; else open door
        doors = find_all(4)
        if any(d[3] == 0 for d in doors):
            memory['phase'] = 4
        else:
            memory['phase'] = 3

    # BFS on visible traversable cells (including agent start). Returns path of positions (including next cell).
    def bfs_to_targets(target_positions, allow_target_cell=False):
        # nodes: positions (x,y) where img[x][y] is visible (o!=0) and traversable OR it's the start
        start = (AG_X, AG_Y)
        q = deque([start])
        prev = {start: None}
        # neighbor directions: up, left, right, down (image coordinates)
        neighs = [(0, -1), (-1, 0), (1, 0), (0, 1)]
        # Quick membership check for targets
        targets_set = set(target_positions)
        if start in targets_set:
            return [start]
        while q:
            cur = q.popleft()
            if cur in targets_set:
                # reconstruct path
                path = []
                p = cur
                while p is not None:
                    path.append(p)
                    p = prev[p]
                path.reverse()
                return path
            cx, cy = cur
            for dx, dy in neighs:
                nx, ny = cx + dx, cy + dy
                if not (0 <= nx < 7 and 0 <= ny < 7):
                    continue
                if (nx, ny) in prev:
                    continue
                o, c, s = cell(nx, ny)
                if o == 0:
                    continue  # unseen treated as blocked
                # allow stepping into traversable cells (floor/empty/goal/open door)
                if is_traversable(o, s) or (allow_target_cell and (nx, ny) in targets_set):
                    prev[(nx, ny)] = cur
                    q.append((nx, ny))
        return None

    # Translate next position (adjacent to agent) into an action.
    # next_pos is a cell adjacent to agent position (or front etc.). Return an action integer.
    def action_for_nextcell(next_pos, final_target=None):
        nx, ny = next_pos
        dx = nx - AG_X
        dy = ny - AG_Y
        # front
        if dx == 0 and dy == -1:
            # if front is key and phase1, pickup; if front is door, toggle; if front is goal, step forward
            o, c, s = front_cell()
            if o == 5 and memory['phase'] == 1:
                return 3
            if o == 4:
                # toggle (will open/unlock if correct key)
                return 5
            if o == 8:
                return 2
            if is_traversable(o, s):
                return 2
            # blocked by non-traversable visible object: try turning
            return 1 if memory['turn_pref'] == 1 else 0
        # left
        if dx == -1 and dy == 0:
            # prefer single rotation to face left
            return 0
        # right
        if dx == 1 and dy == 0:
            return 1
        # back
        if dx == 0 and dy == 1:
            # need two turns; pick preferred single turn (will likely be followed by another call)
            return 1 if memory['turn_pref'] == 1 else 0
        # fallback: rotate to explore
        return 1 if memory['turn_pref'] == 1 else 0

    # Build target positions for BFS depending on phase/type
    def plan_to_key():
        keys = find_all(5)
        if not keys:
            return None
        # For each key, consider adjacent traversable visible cells as candidate targets (where agent can stand to pickup)
        candidates = []
        neighs = [(0, -1), (-1, 0), (1, 0), (0, 1)]
        for kx, ky, kc, ks in keys:
            for dx, dy in neighs:
                nx, ny = kx + dx, ky + dy
                if not (0 <= nx < 7 and 0 <= ny < 7):
                    continue
                o, c, s = cell(nx, ny)
                if o == 0:
                    continue
                if is_traversable(o, s) or (nx == AG_X and ny == AG_Y):
                    candidates.append(((nx, ny), (kx, ky)))
        if not candidates:
            return None
        # Choose reachable candidate with shortest BFS path
        best_path = None
        best_info = None
        for (nx, ny), (kx, ky) in candidates:
            path = bfs_to_targets([(nx, ny)])
            if path:
                if best_path is None or len(path) < len(best_path) or (len(path) == len(best_path) and manhattan((nx, ny), (kx, ky)) < manhattan(best_info[0], best_info[1])):
                    best_path = path
                    best_info = ((nx, ny), (kx, ky))
        return (best_path, best_info) if best_path else None

    def plan_to_door():
        doors = find_all(4)
        if not doors:
            return None
        # For each door, consider adjacent traversable visible cells as candidate positions from which to toggle
        candidates = []
        neighs = [(0, -1), (-1, 0), (1, 0), (0, 1)]
        for dxo, dyo, dcol, dstate in doors:
            for dx, dy in neighs:
                nx, ny = dxo + dx, dyo + dy
                if not (0 <= nx < 7 and 0 <= ny < 7):
                    continue
                o, c, s = cell(nx, ny)
                if o == 0:
                    continue
                if is_traversable(o, s) or (nx == AG_X and ny == AG_Y):
                    candidates.append(((nx, ny), (dxo, dyo), dstate))
        if not candidates:
            return None
        best_path = None
        best_info = None
        for (nx, ny), (dxo, dyo), dstate in candidates:
            path = bfs_to_targets([(nx, ny)])
            if path:
                if best_path is None or len(path) < len(best_path):
                    best_path = path
                    best_info = ((nx, ny), (dxo, dyo), dstate)
        return (best_path, best_info) if best_path else None

    def plan_to_goal():
        goals = find_all(8)
        if not goals:
            return None
        # goal cell itself can be entered (forward allowed), so BFS target is goal cell
        best_path = None
        best_goal = None
        for gx, gy, gcol, gs in goals:
            path = bfs_to_targets([(gx, gy)], allow_target_cell=True)
            if path:
                if best_path is None or len(path) < len(best_path):
                    best_path = path
                    best_goal = (gx, gy)
        return (best_path, best_goal) if best_path else None

    # Exploration when no plan can be formed: prefer forward if traversable, else rotate using turn_pref,
    # but try to avoid repeatedly choosing same rotation: flip if stuck.
    def explore_step():
        of, cf, sf = front_cell()
        if of != 0 and is_traversable(of, sf):
            return 2
        # if front unseen (0), try turning to get new view, but alternate preference if stuck
        if memory['turn_pref'] == 1:
            return 1
        else:
            return 0

    # MAIN DECISION
    action = None

    if memory['phase'] == 1:
        plan_info = plan_to_key()
        if plan_info:
            path, info = plan_info
            # path is list of positions from agent to target-adj cell (includes start)
            if len(path) >= 2:
                next_cell = path[1]
                action = action_for_nextcell(next_cell, final_target=info[1])
            else:
                # already standing adjacent to key: ensure pickup if key is in front
                of, cf, sf = front_cell()
                if of == 5:
                    action = 3
                else:
                    # try exploring or rotating to face the key (if it's to the side)
                    action = explore_step()
        else:
            action = explore_step()

    elif memory['phase'] == 3:
        # plan to door
        plan_info = plan_to_door()
        if plan_info:
            path, info = plan_info
            adj_cell, door_cell, dstate = info  # adj_cell is where to stand, door_cell is door coords
            if len(path) >= 2:
                next_cell = path[1]
                action = action_for_nextcell(next_cell, final_target=door_cell)
            else:
                # we are on adj_cell. Determine relative position of door to agent and act to toggle.
                dx = door_cell[0] - AG_X
                dy = door_cell[1] - AG_Y
                # if door now front
                if dx == 0 and dy == -1:
                    # toggle (open/unlock)
                    action = 5
                elif dx == 1 and dy == 0:
                    action = 1  # turn right to face door
                elif dx == -1 and dy == 0:
                    action = 0  # turn left
                elif dx == 0 and dy == 1:
                    # door behind: rotate (prefer right then right)
                    action = 1 if memory['turn_pref'] == 1 else 0
                else:
                    action = explore_step()
        else:
            action = explore_step()

    elif memory['phase'] == 4:
        plan_info = plan_to_goal()
        if plan_info:
            path, goal_cell = plan_info
            if len(path) >= 2:
                next_cell = path[1]
                action = action_for_nextcell(next_cell, final_target=goal_cell)
            else:
                # standing on goal? forward to enter/complete
                of, cf, sf = front_cell()
                if of == 8:
                    action = 2
                else:
                    action = explore_step()
        else:
            # If open door front, go through
            of, cf, sf = front_cell()
            if of == 4 and sf == 0 and is_traversable(of, sf):
                action = 2
            else:
                action = explore_step()
    else:
        action = explore_step()

    # Robustness: avoid issuing pickup/toggle when front is unseen or wrong object
    if action == 3:
        of, cf, sf = front_cell()
        if of != 5:
            # avoid useless pickup
            action = explore_step()
    if action == 5:
        of, cf, sf = front_cell()
        if of != 4:
            action = explore_step()

    # Avoid repeating the same rotation many times with no forward/view change:
    if action in (0, 1):
        # if we output same rotation last time and view didn't change, consider switching
        if memory.get('last_output') == action and memory['stuck_steps'] > 3:
            # flip preference and pick the other rotation
            memory['turn_pref'] = 1 - memory['turn_pref']
            action = 1 if memory['turn_pref'] == 1 else 0

    # Save last output (so we can compare in subsequent steps if desired)
    memory['last_output'] = action

    return int(action)
