# RLingua controller kc_full (keycorridor_s3r3, full information). Written by gpt-5-mini following RLingua Appendix B.A;
# selected round 1 (20/20), then speed-only feedback (19/20, 43.05 ms/call). Generated by scripts/rlingua_controllers_20261005.py.
from collections import deque

A_TURN_LEFT = 0
A_TURN_RIGHT = 1
A_FORWARD = 2
A_PICKUP = 3
A_DROP = 4
A_TOGGLE = 5
A_DONE = 6

# direction vectors: 0 east, 1 south, 2 west, 3 north
DIR_VECS = [(1, 0), (0, 1), (-1, 0), (0, -1)]


def controller(state) -> int:
    """
    Optimized planner: performs a bounded BFS over a compact mutable-state representation
    (only dynamic objects like doors, keys, balls, boxes) rather than copying the whole grid.
    Returns the first action of a short plan that results in carrying the ball when found.
    Falls back to a small safe heuristic if no plan is found within limits.
    """
    width = state['width']
    height = state['height']
    grid = state['grid']
    init_pos = tuple(state['agent_pos'])
    init_dir = int(state['agent_dir'])
    carrying = None if state['carrying'] is None else {'type': state['carrying']['type'], 'color': state['carrying'].get('color')}

    def in_bounds(x, y):
        return 0 <= x < width and 0 <= y < height

    # Build a compact map of dynamic cells (those that can change or be picked up/moved)
    # We copy their dicts so we can mutate copies safely in simulation.
    dynamic_types = {'door', 'key', 'ball', 'box'}
    init_dyn = {}
    for y in range(height):
        row = grid[y]
        for x in range(width):
            c = row[x]
            if c is None:
                continue
            if c.get('type') in dynamic_types:
                # shallow copy the cell dict to detach from original grid objects
                init_dyn[(x, y)] = dict(c)

    # Helper to retrieve a cell considering dynamic map first, then original grid
    def cell_at_dyn(dyn, x, y):
        if not in_bounds(x, y):
            return {'type': 'wall'}
        key = (x, y)
        if key in dyn:
            return dyn[key]
        return grid[y][x]

    def front_coord(pos, dir):
        dx, dy = DIR_VECS[dir]
        return (pos[0] + dx, pos[1] + dy)

    # Serialize dynamic map to a tuple for visited set (small since few dynamic objects)
    def serialize_dyn(dyn):
        items = []
        for (x, y), c in dyn.items():
            t = c.get('type')
            if t == 'door':
                items.append((x, y, 'door', c.get('color'), bool(c.get('is_open')), bool(c.get('is_locked'))))
            else:
                # key, ball, box
                items.append((x, y, t, c.get('color')))
        items.sort()
        return tuple(items)

    def serialize_carry(c):
        if c is None:
            return None
        return (c.get('type'), c.get('color'))

    # Simulate an action on a (dyn, pos, dir, carry) state; return new tuple or None if invalid
    def simulate(dyn, pos, dir, carry, action):
        x, y = pos
        fx, fy = front_coord(pos, dir)
        front = cell_at_dyn(dyn, fx, fy)

        # Turning
        if action == A_TURN_LEFT:
            return dyn, pos, (dir - 1) % 4, carry
        if action == A_TURN_RIGHT:
            return dyn, pos, (dir + 1) % 4, carry

        # PICKUP
        if action == A_PICKUP:
            if carry is not None:
                return None
            if not in_bounds(fx, fy):
                return None
            if front is None:
                return None
            t = front.get('type')
            if t not in ('key', 'ball'):
                return None
            # remove the object from dyn (or create dyn entry removal)
            new_dyn = dyn.copy()
            # If the object was present in original grid but not in dyn, it's static (shouldn't happen for key/ball)
            if (fx, fy) in new_dyn:
                del new_dyn[(fx, fy)]
            else:
                # If static cell holds key/ball (unlikely), treat as unpickable
                return None
            new_carry = {'type': t, 'color': front.get('color')}
            return new_dyn, pos, dir, new_carry

        # DROP
        if action == A_DROP:
            if carry is None:
                return None
            if not in_bounds(fx, fy):
                return None
            # front cell must be empty floor in both dyn and static grid
            if (fx, fy) in dyn:
                return None
            static_front = grid[fy][fx]
            if static_front is not None:
                return None
            new_dyn = dyn.copy()
            new_dyn[(fx, fy)] = {'type': carry['type'], 'color': carry.get('color')}
            return new_dyn, pos, dir, None

        # TOGGLE: open/close door or unlock if carrying key
        if action == A_TOGGLE:
            if not in_bounds(fx, fy):
                return None
            front_cell = cell_at_dyn(dyn, fx, fy)
            if front_cell is None or front_cell.get('type') != 'door':
                return None
            # mutate door: need copy
            new_dyn = dyn.copy()
            # ensure we operate on a dict copy
            door = dict(front_cell)
            if door.get('is_locked'):
                # can only unlock if carrying matching key
                if carry is not None and carry.get('type') == 'key' and carry.get('color') == door.get('color'):
                    door['is_locked'] = False
                    door['is_open'] = True
                    new_dyn[(fx, fy)] = door
                    return new_dyn, pos, dir, carry
                else:
                    return None
            else:
                door['is_open'] = not door.get('is_open', False)
                new_dyn[(fx, fy)] = door
                return new_dyn, pos, dir, carry

        # FORWARD
        if action == A_FORWARD:
            if not in_bounds(fx, fy):
                return None
            f = cell_at_dyn(dyn, fx, fy)
            # forward allowed if empty floor (None), open door, or goal (static)
            if f is None:
                return dyn, (fx, fy), dir, carry
            if f.get('type') == 'door':
                if f.get('is_open'):
                    return dyn, (fx, fy), dir, carry
                else:
                    return None
            if f.get('type') == 'goal':
                return dyn, (fx, fy), dir, carry
            # blocked by key/ball/box/wall/lava
            return None

        # DONE
        if action == A_DONE:
            return dyn, pos, dir, carry

        return None

    # Quick check: if already carrying ball -> done
    if carrying is not None and carrying.get('type') == 'ball':
        return A_DONE

    # BFS over (dyn, pos, dir, carry) but dyn is compact
    start_key = (init_pos, init_dir, serialize_carry(carrying), serialize_dyn(init_dyn))
    q = deque()
    q.append((init_dyn, init_pos, init_dir, carrying))
    visited = {start_key: None}
    parent = {start_key: None}
    parent_action = {start_key: None}

    MAX_EXPAND = 3000
    expansions = 0
    found_key = None

    # Actions order: pickup/toggle/drop/forward/turn_left/turn_right as before
    ACTION_ORDER = (A_PICKUP, A_TOGGLE, A_DROP, A_FORWARD, A_TURN_LEFT, A_TURN_RIGHT)

    while q and expansions < MAX_EXPAND:
        dyn, pos, dir, carry = q.popleft()
        expansions += 1

        # goal test
        if carry is not None and carry.get('type') == 'ball':
            found_key = (pos, dir, serialize_carry(carry), serialize_dyn(dyn))
            break

        for a in ACTION_ORDER:
            res = simulate(dyn, pos, dir, carry, a)
            if res is None:
                continue
            ndyn, npos, ndir, ncarry = res
            key = (npos, ndir, serialize_carry(ncarry), serialize_dyn(ndyn))
            if key in visited:
                continue
            visited[key] = True
            parent[key] = (pos, dir, serialize_carry(carry), serialize_dyn(dyn))
            parent_action[key] = a
            q.append((ndyn, npos, ndir, ncarry))

    if found_key is not None:
        # backtrack to first action
        k = found_key
        act = None
        while parent[k] is not None:
            act = parent_action[k]
            k = parent[k]
        if act is None:
            return A_DONE
        return act

    # If no plan found within limit, fallback to simple heuristics (safe, small):
    # If front has a key/ball and can pick -> pickup
    fx, fy = front_coord(init_pos, init_dir)
    if in_bounds(fx, fy):
        frontcell = cell_at_dyn(init_dyn, fx, fy)
        if frontcell is not None and frontcell.get('type') in ('key', 'ball') and carrying is None:
            return A_PICKUP
        if frontcell is not None and frontcell.get('type') == 'door':
            # if locked and we carry key -> toggle
            if frontcell.get('is_locked') and carrying is not None and carrying.get('type') == 'key' and carrying.get('color') == frontcell.get('color'):
                return A_TOGGLE
            # if closed and unlocked -> toggle
            if not frontcell.get('is_open') and not frontcell.get('is_locked'):
                return A_TOGGLE
        # forward if clear
        if frontcell is None or (frontcell.get('type') == 'door' and frontcell.get('is_open')) or (frontcell is not None and frontcell.get('type') == 'goal'):
            return A_FORWARD

    # else rotate to explore
    return A_TURN_RIGHT
