# RLingua controller kc_view (keycorridor_s3r3, view information). Written by gpt-5-mini following RLingua Appendix B.A;
# selected round 4 (0/20 alone, 4/20 with another policy acting). Generated by scripts/rlingua_controllers_20261005.py.
def controller(obs, memory) -> int:
    """
    Refined staged controller for the key + locked-door + ball task.

    Improvements based on test traces:
      - When carrying the key but no door is found for several steps, perform an aggressive
        exploration pattern (turn + forward) to escape local loops instead of spinning.
      - Track 'no_door_steps' when carrying key and no door seen, reset when any door visible.
      - Flip turning preference after long runs of turns to avoid getting stuck turning one way.
      - Always record prev_front/prev_center before returning (used to detect successful forward).
    """
    # Actions
    TURN_LEFT = 0
    TURN_RIGHT = 1
    FORWARD = 2
    PICKUP = 3
    DROP = 4
    TOGGLE = 5
    DONE = 6

    img = obs['image']
    AX, AY = 3, 6
    FX, FY = 3, 5

    # helpers
    def cell(x, y):
        if 0 <= x <= 6 and 0 <= y <= 6:
            return tuple(img[x][y])
        return (0, 0, 0)

    def obj_at(x, y):
        return cell(x, y)[0]

    def color_at(x, y):
        return cell(x, y)[1]

    def state_at(x, y):
        return cell(x, y)[2]

    def find_all(obj_type):
        res = []
        for x in range(7):
            for y in range(7):
                if obj_at(x, y) == obj_type:
                    res.append((x, y))
        return res

    # initialize memory fields
    if 'phase' not in memory:
        memory.update({
            'phase': 1,
            'key_color': None,
            'dropped_key': False,
            'turn_prefer': TURN_RIGHT,
            'consec_turns': 0,
            'consec_forward_fail': 0,
            'prev_front': None,
            'prev_center': None,
            'last_executed': None,
            'no_door_steps': 0,        # counts steps while carrying key and no door visible
            'aggr_step': 0,            # step counter used for aggressive exploration pattern
        })

    # record executed action (what actually happened)
    executed = obs.get('last_action', None)
    memory['last_executed'] = executed

    # detect whether a forward actually moved us:
    moved_forward = False
    if executed == FORWARD and memory.get('prev_front') is not None:
        # if previous front cell (content) equals current center content, we've moved forward
        if memory['prev_front'] == img[AX][AY]:
            moved_forward = True

    # update counters
    if executed in (TURN_LEFT, TURN_RIGHT):
        memory['consec_turns'] = memory.get('consec_turns', 0) + 1
    else:
        memory['consec_turns'] = 0

    if executed == FORWARD:
        if moved_forward:
            memory['consec_forward_fail'] = 0
        else:
            memory['consec_forward_fail'] = memory.get('consec_forward_fail', 0) + 1
    else:
        # non-forward resets forward fail only moderately
        memory['consec_forward_fail'] = max(0, memory.get('consec_forward_fail', 0) - 1)

    # perception
    keys = find_all(5)
    balls = find_all(6)
    doors = find_all(4)
    carried_obj = obj_at(AX, AY)   # 5 key, 6 ball, 1 nothing
    carried_color = color_at(AX, AY)

    # auto-phase updates
    if carried_obj == 5:
        memory['key_color'] = carried_color
        if memory['phase'] < 4:
            memory['phase'] = 4

    # record that we dropped recently
    if executed == DROP:
        memory['dropped_key'] = True

    # If ball directly in front and not carrying key and we have dropped key earlier, pick it
    if obj_at(FX, FY) == 6 and carried_obj != 5 and memory.get('dropped_key', False):
        memory['phase'] = 8

    # If we see a ball and are carrying a key, we'll want to drop it (phase 7)
    if balls and carried_obj == 5 and memory.get('phase', 0) < 7:
        memory['phase'] = 7

    # basic utilities
    def forward_allowed():
        o = obj_at(FX, FY)
        if o in (1, 3, 8):
            return True
        if o == 4:
            return state_at(FX, FY) == 0  # open door allows forward
        return False

    def nearest(coords):
        return min(coords, key=lambda p: abs(p[0]-AX) + abs(p[1]-AY))

    def steer_make_front(tx, ty):
        # Return action to make (tx,ty) become front (FX,FY).
        if (tx, ty) == (FX, FY):
            return None
        if tx == AX:
            if forward_allowed():
                return FORWARD
            if obj_at(FX, FY) == 4:
                return TOGGLE
            return memory['turn_prefer']
        if tx < AX:
            return TURN_LEFT
        return TURN_RIGHT

    # safe forward: avoid attempting forward into non-walkable objects repeatedly
    def safe_forward():
        if forward_allowed():
            # if we've had recent failed forwards, prefer turning instead of repeatedly forward
            if memory.get('consec_forward_fail', 0) >= 2:
                # toggle turn preference to try new direction
                memory['turn_prefer'] = TURN_LEFT if memory.get('turn_prefer') == TURN_RIGHT else TURN_RIGHT
                memory['consec_turns'] += 1
                return memory['turn_prefer']
            return FORWARD
        # if door in front, try toggle (open/unlock)
        if obj_at(FX, FY) == 4:
            return TOGGLE
        # else turn preferred direction
        if memory.get('consec_turns', 0) >= 4:
            # alternate if stuck turning
            memory['turn_prefer'] = TURN_LEFT if memory.get('turn_prefer') == TURN_RIGHT else TURN_RIGHT
            memory['consec_turns'] = 0
        return memory['turn_prefer']

    # helper to set prev_front/prev_center and return action
    def record_and_return(a):
        memory['prev_front'] = cell(FX, FY)
        memory['prev_center'] = cell(AX, AY)
        # maintain aggressive pattern counter
        memory['aggr_step'] = (memory.get('aggr_step', 0) + 1) % 1000
        return a

    phase = memory['phase']

    # PHASE 1: SEARCH_KEY
    if phase == 1:
        if keys:
            memory['phase'] = 2
            phase = 2
        else:
            # exploration: forward if possible, else turn preferred
            if forward_allowed() and memory.get('consec_forward_fail', 0) < 2:
                return record_and_return(FORWARD)
            return record_and_return(memory['turn_prefer'])

    # PHASE 2: GOTO_KEY
    if phase == 2:
        if carried_obj == 5:
            memory['phase'] = 4
            return record_and_return(memory['turn_prefer'])
        if not keys:
            memory['phase'] = 1
            return record_and_return(memory['turn_prefer'])
        kx, ky = nearest(keys)
        if (kx, ky) == (FX, FY):
            return record_and_return(PICKUP)
        act = steer_make_front(kx, ky)
        if act is None:
            return record_and_return(safe_forward())
        return record_and_return(act)

    # PHASE 4: GOTO_DOOR (carrying key)
    if phase == 4:
        if carried_obj != 5:
            memory['phase'] = 1
            return record_and_return(memory['turn_prefer'])
        keycol = memory.get('key_color', carried_color)
        locked_doors = [(dx, dy) for (dx, dy) in doors if state_at(dx, dy) == 2 and color_at(dx, dy) == keycol]
        # If we see any door at all, reset no_door_steps
        if doors:
            memory['no_door_steps'] = 0
        else:
            memory['no_door_steps'] = memory.get('no_door_steps', 0) + 1

        # Aggressive exploration if no door seen for some steps
        if memory.get('no_door_steps', 0) >= 6:
            # perform a short deterministic pattern to escape local area:
            # alternate: TURN_RIGHT, FORWARD, TURN_LEFT, FORWARD, repeat
            step = memory.get('aggr_step', 0) % 4
            if step == 0:
                return record_and_return(TURN_RIGHT)
            elif step in (1, 3):
                # try forward when possible, otherwise turn
                if forward_allowed():
                    return record_and_return(FORWARD)
                else:
                    # if blocked by door in front, toggle it
                    if obj_at(FX, FY) == 4:
                        return record_and_return(TOGGLE)
                    # else alternate turn
                    return record_and_return(TURN_LEFT if (memory.get('aggr_step', 0) % 8) < 4 else TURN_RIGHT)
            else:  # step == 2
                return record_and_return(TURN_LEFT)

        # Normal behavior if locked door(s) visible:
        if locked_doors:
            dx, dy = nearest(locked_doors)
            if (dx, dy) == (FX, FY):
                return record_and_return(TOGGLE)
            act = steer_make_front(dx, dy)
            if act is None:
                return record_and_return(safe_forward())
            return record_and_return(act)

        # No locked doors visible: try to find any door (maybe unlocked or closed) to approach
        visible_doors = [(dx, dy) for (dx, dy) in doors]
        if visible_doors:
            ddx, ddy = nearest(visible_doors)
            if (ddx, ddy) == (FX, FY):
                # open/unlock if possible
                return record_and_return(TOGGLE)
            act = steer_make_front(ddx, ddy)
            if act is None:
                return record_and_return(safe_forward())
            return record_and_return(act)

        # Otherwise explore forward/turn to find door
        return record_and_return(safe_forward())

    # If we were in phase 4 and a door became open, move into it (phase 6)
    if phase == 4:
        if any(obj_at(dx, dy) == 4 and state_at(dx, dy) == 0 for (dx, dy) in doors):
            memory['phase'] = 6
            phase = 6

    # PHASE 6: ENTER_ROOM (move through open door)
    if phase == 6:
        # If an open door or walkable tile is in front, go forward
        if forward_allowed():
            return record_and_return(FORWARD)
        if obj_at(FX, FY) == 4:
            # try to toggle (open) if closed
            return record_and_return(TOGGLE)
        # else explore
        return record_and_return(memory['turn_prefer'])

    # If carrying key and balls visible, move to drop stage
    if balls and carried_obj == 5 and memory.get('phase', 0) < 7:
        memory['phase'] = 7
        phase = 7

    # PHASE 7: DROP_KEY (drop key somewhere appropriate before picking ball)
    if phase == 7:
        if carried_obj != 5:
            memory['dropped_key'] = True
            memory['phase'] = 8
            return record_and_return(memory['turn_prefer'])
        # Prefer to drop in front if empty/floor
        if obj_at(FX, FY) in (1, 3):
            return record_and_return(DROP)
        # Try to find empty neighbor of any visible ball
        if balls:
            bx, by = nearest(balls)
            neighbors = [(bx-1, by), (bx+1, by), (bx, by-1), (bx, by+1)]
            empties = [(nx, ny) for (nx, ny) in neighbors if 0 <= nx <= 6 and 0 <= ny <= 6 and obj_at(nx, ny) == 1]
            # if front is one of them, drop
            if (FX, FY) in empties:
                return record_and_return(DROP)
            if empties:
                tx, ty = nearest(empties)
                act = steer_make_front(tx, ty)
                if act is None:
                    return record_and_return(DROP)
                return record_and_return(act)
        # If no balls or no empty neighbors, try to find any empty/floor to drop into
        empties_all = []
        for x in range(7):
            for y in range(7):
                if obj_at(x, y) in (1, 3):
                    empties_all.append((x, y))
        if empties_all:
            tx, ty = nearest(empties_all)
            act = steer_make_front(tx, ty)
            if act is None:
                return record_and_return(DROP)
            return record_and_return(act)
        # fallback: try to move around to reveal empty tiles
        if forward_allowed():
            return record_and_return(FORWARD)
        # if door is in front, try toggle; else turn
        if obj_at(FX, FY) == 4:
            return record_and_return(TOGGLE)
        return record_and_return(memory['turn_prefer'])

    # PHASE 8: PICK_BALL
    if phase == 8:
        if carried_obj == 5:
            memory['phase'] = 7
            return record_and_return(memory['turn_prefer'])
        if obj_at(FX, FY) == 6:
            return record_and_return(PICKUP)
        if balls:
            bx, by = nearest(balls)
            act = steer_make_front(bx, by)
            if act is None:
                return record_and_return(FORWARD if forward_allowed() else memory['turn_prefer'])
            return record_and_return(act)
        # explore looking for ball
        if forward_allowed():
            return record_and_return(FORWARD)
        return record_and_return(memory['turn_prefer'])

    # Fallback: explore safely
    return record_and_return(safe_forward())
