# RLingua controller mr_full (multiroom_n6, full information). Written by gpt-5-mini following RLingua Appendix B.A;
# selected round 1 (20/20 feedback episodes). Generated by scripts/rlingua_controllers_20261005.py.
def controller(state) -> int:
    """
    Improved staged controller with simple pathfinding and persistent memory to avoid local oscillation.
    Strategy summary:
    - Persist visited cells and a planned path across calls (stored on the function object).
    - Try to find a path to the goal first (respecting locked doors unless we hold a matching key).
    - If goal not reachable, try to find the nearest key.
    - If no key found, try to explore toward the nearest unvisited empty floor cell.
    - Follow the planned path: turn toward the next step, open doors when adjacent, pick up keys/objects when blocking the path.
    - If a locked door blocks the planned path and we don't have the matching key, discard the plan and search for a key.
    """
    from collections import deque

    # Initialize persistent memory on the controller function
    if not hasattr(controller, "mem"):
        controller.mem = {
            "visited": set(),   # set of (x,y)
            "path": [],         # list of positions (x,y) to follow (excluding current pos)
            "target": None,     # 'goal', 'key', 'explore' or None
        }
    mem = controller.mem

    W = state['width']
    H = state['height']
    grid = state['grid']
    ax, ay = state['agent_pos']
    ad = state['agent_dir']  # 0 east,1 south,2 west,3 north
    carrying = state['carrying']  # None or {'type','color'}

    # Helpers
    def in_bounds(x, y):
        return 0 <= x < W and 0 <= y < H

    def cell_at(x, y):
        return grid[y][x]

    # Mark visited
    mem['visited'].add((ax, ay))

    # Directions
    DIRS = [(1, 0), (0, 1), (-1, 0), (0, -1)]

    # Compute cell in front
    fx = ax + DIRS[ad][0]
    fy = ay + DIRS[ad][1]
    front = cell_at(fx, fy) if in_bounds(fx, fy) else None

    # Immediate reactions
    # If goal directly in front -> move into it.
    if in_bounds(fx, fy) and front is not None and front.get('type') == 'goal':
        return 2  # forward

    # If a key is in front and we are not carrying -> pick it up
    if in_bounds(fx, fy) and front is not None and front.get('type') == 'key' and carrying is None:
        return 3  # pickup

    # If a ball/box is in front and we are not carrying -> pickup (so we can clear the way)
    if in_bounds(fx, fy) and front is not None and front.get('type') in ('ball', 'box') and carrying is None:
        return 3  # pickup

    # Pathfinding BFS: returns a path (list of positions) from start (sx,sy) to an end satisfying goal_test
    def bfs(start, goal_test):
        sx, sy = start
        q = deque()
        q.append((sx, sy))
        prev = { (sx, sy): None }
        while q:
            x, y = q.popleft()
            if goal_test((x, y)):
                # reconstruct path (inclusive of start and goal)
                path = []
                cur = (x, y)
                while cur is not None:
                    path.append(cur)
                    cur = prev[cur]
                path.reverse()  # start...goal
                return path
            for d in range(4):
                nx = x + DIRS[d][0]
                ny = y + DIRS[d][1]
                if not in_bounds(nx, ny):
                    continue
                if (nx, ny) in prev:
                    continue
                c = cell_at(nx, ny)
                # Impassable: wall, lava
                if c is not None and c.get('type') in ('wall', 'lava'):
                    continue
                # Locked door handling: cannot pass unless we have the matching key
                if c is not None and c.get('type') == 'door' and c.get('is_locked', False):
                    if carrying is None or carrying.get('type') != 'key' or carrying.get('color') != c.get('color'):
                        # cannot pass through this door in current state
                        continue
                # Otherwise consider neighbor reachable (we allow closed doors/keys/boxes because they can be toggled/picked)
                prev[(nx, ny)] = (x, y)
                q.append((nx, ny))
        return None

    # Helper to set a new plan (path excluding current position)
    def set_plan(path, target_name):
        if path is None:
            mem['path'] = []
            mem['target'] = None
        else:
            # path is list from current pos (ax,ay) to goal; drop the current pos
            if len(path) >= 2 and path[0] == (ax, ay):
                mem['path'] = path[1:]
            else:
                # Unexpected: just use whole path as plan
                mem['path'] = path[:]
            mem['target'] = target_name

    # If we don't have a plan or plan is exhausted/invalid, create one
    def plan_if_needed():
        # Validate existing path: ensure it's still valid (next step not blocked by an unopenable locked door, etc.)
        if mem['path']:
            nx, ny = mem['path'][0]
            # if next step is adjacent (should be), check if it's a locked door we can't open or an immovable obstacle
            if not (abs(nx - ax) + abs(ny - ay) == 1):
                # path no longer valid
                mem['path'] = []
                mem['target'] = None
            else:
                c = cell_at(nx, ny)
                if c is not None and c.get('type') == 'door' and c.get('is_locked', False):
                    # locked door in the way but we don't have the key -> invalidate to search for key
                    if carrying is None or carrying.get('type') != 'key' or carrying.get('color') != c.get('color'):
                        mem['path'] = []
                        mem['target'] = None

        if mem['path']:
            return  # keep current plan

        # 1) Try to find a path to the goal
        path_goal = bfs((ax, ay), lambda p: (cell_at(p[0], p[1]) is not None and cell_at(p[0], p[1]).get('type') == 'goal'))
        if path_goal:
            set_plan(path_goal, 'goal')
            return

        # 2) Try to find nearest key (we might need it to unlock doors)
        path_key = bfs((ax, ay), lambda p: (cell_at(p[0], p[1]) is not None and cell_at(p[0], p[1]).get('type') == 'key'))
        if path_key:
            set_plan(path_key, 'key')
            return

        # 3) Explore: find nearest unvisited empty floor cell (None)
        path_explore = bfs((ax, ay), lambda p: (cell_at(p[0], p[1]) is None and (p[0], p[1]) not in mem['visited']))
        if path_explore:
            set_plan(path_explore, 'explore')
            return

        # 4) As a fallback, try any reachable empty cell (even if visited) to avoid stalling
        path_any = bfs((ax, ay), lambda p: (cell_at(p[0], p[1]) is None))
        if path_any:
            set_plan(path_any, 'explore')
            return

        # 5) Nothing to plan -> clear
        set_plan(None, None)

    plan_if_needed()

    # If we have a plan, follow it
    if mem['path']:
        next_pos = mem['path'][0]
        nx, ny = next_pos
        # If next_pos is no longer adjacent (rare) or invalid, drop plan
        if abs(nx - ax) + abs(ny - ay) != 1:
            mem['path'] = []
            mem['target'] = None
            # fallback to reactive behavior below
        else:
            # decide action to move toward next_pos
            # desired direction
            if nx > ax:
                desired_dir = 0
            elif ny > ay:
                desired_dir = 1
            elif nx < ax:
                desired_dir = 2
            else:
                desired_dir = 3

            # get the cell in front (recompute in case orientation needs change)
            front_x = ax + DIRS[ad][0]
            front_y = ay + DIRS[ad][1]
            front_cell = cell_at(front_x, front_y) if in_bounds(front_x, front_y) else None

            # If the next_pos is exactly the front cell, we may need to toggle or pickup before moving
            if (front_x, front_y) == (nx, ny):
                c = front_cell
                if c is None:
                    # clear: move forward
                    # consume this step of path after moving (the environment will update mem on next call)
                    return 2  # forward
                t = c.get('type')
                if t == 'door':
                    if c.get('is_open', False):
                        return 2  # forward
                    # closed door
                    if c.get('is_locked', False):
                        # if we have the right key -> toggle (unlock/open)
                        if carrying is not None and carrying.get('type') == 'key' and carrying.get('color') == c.get('color'):
                            return 5  # toggle (will unlock/open)
                        else:
                            # can't open: invalidate plan so we'll search for a key
                            mem['path'] = []
                            mem['target'] = None
                            return 1  # turn_right to change orientation while replanning
                    else:
                        # closed but not locked -> open
                        return 5  # toggle
                if t == 'key':
                    if carrying is None:
                        return 3  # pickup first, then next step will be forward
                    else:
                        # can't pick up; invalidate path and replan (to go around)
                        mem['path'] = []
                        mem['target'] = None
                        return 1
                if t in ('ball', 'box'):
                    if carrying is None:
                        return 3  # pickup to clear the way
                    else:
                        # cannot pick up -> replan
                        mem['path'] = []
                        mem['target'] = None
                        return 1
                # any other type (open door, goal etc.) -> forward
                return 2
            else:
                # need to orient toward desired_dir
                delta = (desired_dir - ad) % 4
                if delta == 0:
                    # facing desired direction but next_pos is not directly in front (shouldn't happen) -> forward as safe choice
                    return 2
                elif delta == 1:
                    return 1  # turn_right
                elif delta == 3:
                    return 0  # turn_left
                else:
                    # opposite direction: choose one turn (right) to begin reorientation
                    return 1

    # No plan or plan invalid: fall back to simple reactive behavior (but avoid pure right-turn oscillation)
    # Prefer moving forward if free and unvisited, else try turning to an orientation that leads to an unvisited cell.
    # 1) If forward is empty floor and unvisited -> go forward
    if in_bounds(fx, fy) and front is None and (fx, fy) not in mem['visited']:
        return 2  # forward

    # 2) Try to find a direction to an adjacent unvisited cell and turn toward it
    for d in (0, 1, 3, 2):  # prefer right, then forward, then left, then back (but will compute desired orientation)
        tx = ax + DIRS[d][0]
        ty = ay + DIRS[d][1]
        if not in_bounds(tx, ty):
            continue
        c = cell_at(tx, ty)
        if c is None and (tx, ty) not in mem['visited']:
            # turn toward d
            delta = (d - ad) % 4
            if delta == 0:
                return 2
            elif delta == 1:
                return 1
            elif delta == 3:
                return 0
            else:
                return 1

    # 3) If forward is open (None or open door or goal) -> go forward
    if in_bounds(fx, fy) and (front is None or (front.get('type') == 'door' and front.get('is_open', False))):
        return 2

    # 4) If forward is a closed door we can open/unlock -> do it
    if in_bounds(fx, fy) and front is not None and front.get('type') == 'door':
        if not front.get('is_open', False):
            if front.get('is_locked', False):
                if carrying is not None and carrying.get('type') == 'key' and carrying.get('color') == front.get('color'):
                    return 5  # unlock/open
                else:
                    # cannot open locked door now; try to reorient and plan
                    # clear existing plan to force search for a key
                    mem['path'] = []
                    mem['target'] = None
                    return 1  # turn_right to change orientation
            else:
                return 5  # open closed door

    # 5) If forward is a key/box/ball and we can pick up -> do so
    if in_bounds(fx, fy) and front is not None and front.get('type') in ('key', 'ball', 'box') and carrying is None:
        return 3  # pickup

    # 6) As a last resort, turn left if we've been turning right a lot; prefer alternating turns to escape oscillation.
    # Maintain a tiny local toggle to avoid repeated right-only behavior
    if not hasattr(controller, "turn_toggle"):
        controller.turn_toggle = False
    controller.turn_toggle = not controller.turn_toggle
    return 0 if controller.turn_toggle else 1  # alternate left/right turns to break loops
