# RLingua controller mr_view (multiroom_n6, view information). Written by gpt-5-mini following RLingua Appendix B.A;
# selected round 0 (0/20 alone, 0/20 with another policy acting). Generated by scripts/rlingua_controllers_20261005.py.
def controller(obs, memory):
    """
    Staged controller for a 6-room chain task.
    Signature: controller(obs, memory) -> int
    Actions: 0 turn_left, 1 turn_right, 2 forward, 3 pickup, 4 drop, 5 toggle, 6 done
    """

    # Helpful aliases
    image = obs.get('image')
    last_action = obs.get('last_action')

    # Sanity: image should be present
    if image is None:
        return 6  # do nothing if no observation

    # The agent is at image[3][6] (carried object) and faces up; front cell is image[3][5]
    def cell_at(col, row):
        # return triple [obj, color, state] or [0,0,0] for unseen
        try:
            return image[col][row]
        except Exception:
            return [0, 0, 0]

    front = cell_at(3, 5)
    carried = cell_at(3, 6)  # carried object (object==1 => nothing)

    # Helpers to inspect the forward column (col 3) for doors/goal/keys
    def find_first_in_col3(obj_id):
        # find smallest row j in column 3 (0..5) where object == obj_id and seen (object != 0)
        for j in range(0, 6):
            c = cell_at(3, j)
            if c[0] == obj_id:
                return j, c
        return None, None

    def find_any(obj_id):
        # find any visible cell with object obj_id anywhere (returns (col,row) or (None,None))
        for i in range(7):
            for j in range(7):
                c = cell_at(i, j)
                if c[0] == obj_id:
                    return i, j
        return None, None

    # Initialize memory defaults
    if 'phase' not in memory:
        memory['phase'] = 1  # phases 1..6 as described
    if 'prev_next_door_row' not in memory:
        memory['prev_next_door_row'] = None

    phase = memory['phase']

    # Detect visible goal anywhere -> switch to phase 6 (go to green goal in last room)
    goal_col, goal_row = find_any(8)
    if goal_col is not None:
        # if a goal is visible, consider we're in the final phase
        phase = 6
        memory['phase'] = 6

    # Detect the nearest door ahead in column 3 (if any)
    next_door_row, next_door_cell = find_first_in_col3(4)  # object id 4 = door

    # If we've progressed past a door since last step, increment phase (but cap at 6)
    prev_row = memory.get('prev_next_door_row')
    if prev_row is not None:
        # If previously there was a door visible ahead and now there is none or it's further away,
        # it's consistent with having passed that door.
        if prev_row is not None and (next_door_row is None or (next_door_row is not None and next_door_row > prev_row)):
            # Increment phase, but don't exceed 6
            if memory['phase'] < 6:
                memory['phase'] = memory['phase'] + 1
                phase = memory['phase']
    # Update stored next door row for next invocation
    memory['prev_next_door_row'] = next_door_row

    # Utility checks
    def is_front_pickable(cell):
        # pickable objects: key (5), ball (6), box (7) - allow picking keys/balls/boxes if possible
        return cell[0] in (5, 6, 7)

    def carrying_key_of_color(color):
        return carried[0] == 5 and carried[1] == color

    # Basic fallback: if front is unseen (0) or a wall (2) and we can rotate to look, rotate right to explore
    if front[0] == 0 or front[0] == 2:
        # rotate to explore
        return 1  # turn_right

    # Phase-based behavior
    # Phases 1..5: "go through the door to Room N+1"
    if 1 <= phase <= 5:
        # If there's a door directly in front:
        if front[0] == 4:
            door_state = front[2]  # 0 open, 1 closed, 2 locked
            door_color = front[1]
            if door_state == 0:
                # open door in front: go through
                return 2  # forward
            elif door_state == 1:
                # closed but not locked: open it
                return 5  # toggle
            else:  # locked
                # If carrying key of same color, unlock (toggle)
                if carrying_key_of_color(door_color):
                    return 5  # toggle (will unlock/open)
                # If a matching key is visible in front column, approach/pick it
                kcol, krow = find_any(5)
                if kcol is not None:
                    # If key is directly in front (same column and adjacent), pick it
                    if kcol == 3 and krow == 5 and carried[0] == 1:
                        return 3  # pickup
                    # If key is somewhere ahead in column 3, move forward to approach it
                    if kcol == 3 and krow is not None and krow < 5:
                        # If front is the key and not adjacent, forward to get closer
                        # If front is locked door blocking, and key is beyond, we cannot reach it;
                        # try to explore (turn_right) to find a key elsewhere.
                        return 1  # turn_right
                # If we cannot reach the key or don't see it, try to look around
                return 1  # turn_right to explore / attempt alternate route
        else:
            # Front is not a door. Handle pickable objects, goal or open floor.
            if front[0] == 8:
                # Goal is directly in front -> move into it (episode will succeed)
                return 2  # forward
            if is_front_pickable(front):
                # If front is a key and we carry nothing, pick it up to help unlock later doors
                if front[0] == 5 and carried[0] == 1:
                    return 3  # pickup
                # If it's a ball/box/key but we already carry something and cannot pick, try to sidestep
                if carried[0] != 1:
                    return 1  # turn_right to avoid blocking object
                # otherwise pick up
                return 3  # pickup
            # Front is empty floor or open door (not door object) -> move forward
            if front[0] in (1, 3):  # 1 empty, 3 floor
                return 2  # forward
            # If front is something unexpected (e.g. lava), avoid by turning
            return 1  # turn_right

    # Phase 6: go to the green goal square in Room 6
    if phase == 6:
        # If goal is visible and directly in front -> go forward to reach it
        if front[0] == 8:
            return 2  # forward

        # If there is goal somewhere in the forward column, move forward to approach it
        gcol, grow = find_first_in_col3(8)
        if gcol is not None:
            # If front is blocked by a closed/locked door, try to open/unlock it
            if front[0] == 4:
                if front[2] == 0:
                    return 2  # forward
                elif front[2] == 1:
                    return 5  # toggle
                else:  # locked
                    if carrying_key_of_color(front[1]):
                        return 5  # toggle (unlock)
                    else:
                        # we see the goal but a locked door blocks it and we don't have the key:
                        # try to look around to find a key
                        kc, kr = find_any(5)
                        if kc is not None:
                            # attempt to head toward any visible key by turning (best-effort)
                            return 1  # turn_right
                        # otherwise explore
                        return 1  # turn_right
            else:
                # front is free -> step forward toward goal
                if front[0] in (1, 3):
                    return 2  # forward
                # if front is pickable and we are empty, pick it if it might be a key; else avoid
                if is_front_pickable(front) and carried[0] == 1:
                    return 3  # pickup
                return 1  # turn_right to avoid obstacle
        # If goal is not in forward column, but visible somewhere:
        if goal_col is not None:
            # try to face it by turning (best-effort)
            # We'll prefer turning towards the side where the goal is visible.
            if goal_col < 3:
                return 0  # turn_left to look left
            elif goal_col > 3:
                return 1  # turn_right to look right
            else:
                # same column but outside view (shouldn't happen), move forward
                return 2
        # If goal not visible at all, proceed forward exploring rooms (to find doors/goals)
        if front[0] in (1, 3):
            return 2  # forward
        if is_front_pickable(front) and carried[0] == 1:
            return 3  # pickup
        # fallback: try to open a door if there is one in front; else turn to explore
        if front[0] == 4:
            if front[2] == 0:
                return 2
            else:
                return 5
        return 1  # turn_right to explore

    # Safe fallback
    return 6  # done (no-op)
